services:
  ziti-controller:
    image: "${ZITI_IMAGE}:${ZITI_VERSION}"
    env_file:
      - ./.env
    ports:
      - ${ZITI_INTERFACE:-0.0.0.0}:${ZITI_CTRL_PORT}:${ZITI_CTRL_PORT}
    environment:
      - ZITI_CTRL_NAME=${ZITI_CTRL_NAME}
      - ZITI_CTRL_EDGE_ADVERTISED_ADDRESS=${ZITI_CTRL_FULLY_QUALIFIED_DOMAIN_NAME}
      - ZITI_CTRL_EDGE_ADVERTISED_PORT=${ZITI_CTRL_PORT}
      - ZITI_CTRL_ADVERTISED_PORT=${ZITI_CTRL_PORT}
      - ZITI_CTRL_EDGE_IP_OVERRIDE=${ZITI_CTRL_EDGE_IP_OVERRIDE:-127.0.0.1}
      - ZITI_EDGE_IDENTITY_ENROLLMENT_DURATION=${ZITI_EDGE_IDENTITY_ENROLLMENT_DURATION}
      - ZITI_ROUTER_ENROLLMENT_DURATION=${ZITI_ROUTER_ENROLLMENT_DURATION}
      - ZITI_USER=${ZITI_USER}
      - ZITI_PWD=${ZITI_PWD}
    networks:
      ziti:
        aliases:
          - ziti-edge-controller
    volumes:
      - ziti-fs:/persistent
    entrypoint:
      - "/var/openziti/scripts/run-controller.sh"

  ziti-controller-init-container:
    image: "${ZITI_IMAGE}:${ZITI_VERSION}"
    depends_on:
      - ziti-controller
    environment:
      - ZITI_CTRL_EDGE_ADVERTISED_ADDRESS=${ZITI_CTRL_FULLY_QUALIFIED_DOMAIN_NAME}
      - ZITI_CTRL_EDGE_ADVERTISED_PORT=${ZITI_CTRL_PORT}
    env_file:
      - ./.env
    networks:
      ziti:
    volumes:
      - ziti-fs:/persistent
    entrypoint:
      - "/var/openziti/scripts/run-with-ziti-cli.sh"
    command:
      - "/var/openziti/scripts/access-control.sh"

  ziti-edge-router:
    image: "${ZITI_IMAGE}:${ZITI_VERSION}"
    env_file:
      - ./.env
    depends_on:
      - ziti-controller
    ports:
      - ${ZITI_INTERFACE:-0.0.0.0}:${ZITI_ROUTER_PORT}:${ZITI_ROUTER_PORT}
    environment:
      - ZITI_ROUTER_ADVERTISED_ADDRESS=${ZITI_ROUTER_FULLY_QUALIFIED_DOMAIN_NAME}
      - ZITI_ROUTER_PORT=${ZITI_ROUTER_PORT}
      - ZITI_ROUTER_LISTENER_BIND_PORT=${ZITI_ROUTER_PORT}
      - ZITI_CTRL_ADVERTISED_ADDRESS=${ZITI_CTRL_FULLY_QUALIFIED_DOMAIN_NAME}
      - ZITI_CTRL_ADVERTISED_PORT=${ZITI_CTRL_PORT}
      - ZITI_CTRL_EDGE_ADVERTISED_ADDRESS=${ZITI_CTRL_FULLY_QUALIFIED_DOMAIN_NAME}
      - ZITI_CTRL_EDGE_ADVERTISED_PORT=${ZITI_CTRL_PORT}
      - ZITI_ROUTER_NAME=${ZITI_ROUTER_NAME}
      - ZITI_ROUTER_ROLES=public
    networks:
      - ziti
    volumes:
      - ziti-fs:/persistent
    entrypoint: /bin/bash
    command: "/var/openziti/scripts/run-router.sh edge"

  ziti-console:
    image: openziti/zac
    working_dir: /usr/src/app
    environment:
      - ZAC_SERVER_CERT_CHAIN=/persistent/pki/${ZITI_FULLY_QUALIFIED_DOMAIN_NAME}-intermediate/certs/${ZITI_FULLY_QUALIFIED_DOMAIN_NAME}-server.cert
      - ZAC_SERVER_KEY=/persistent/pki/${ZITI_FULLY_QUALIFIED_DOMAIN_NAME}-intermediate/keys/${ZITI_FULLY_QUALIFIED_DOMAIN_NAME}-server.key
      - ZITI_CTRL_EDGE_ADVERTISED_ADDRESS=${ZITI_FULLY_QUALIFIED_DOMAIN_NAME}
      - ZITI_CTRL_EDGE_ADVERTISED_PORT=${ZITI_CTRL_PORT}
      - ZITI_CTRL_NAME=${ZITI_CTRL_NAME:-ziti-edge-controller}
      - PORTTLS=8443
    depends_on:
      - ziti-controller
    ports:
      - ${ZITI_INTERFACE:-0.0.0.0}:8443:8443
    volumes:
      - ziti-fs:/persistent
    networks:
      - ziti

networks:
  ziti:

volumes:
  ziti-fs:

